spring:
  data:
    redis:
      host: ${EC2_IPV4}
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATABASE_URL}
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      credentials:
        access-key: ${AWS_S3_ACCESSKEY}
        secret-key: ${AWS_S3_SECRETKEY}
      region:
        static: ${AWS_S3_REGION}
        auto: false
      stack:
        auto: false
  encrypt:
    key: ${AES_ENCRYPTION_KEY}

codef:
  access-token: ${ACCESS_TOKEN}
  client-id: ${CLIENT_ID}
  seceret-key: ${SECERET_KEY}
  public-key: ${PUBLIC_KEY}

google-map:
  api-key: ${GOOGLE_CLOUD_API_KEY}

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

openai:
  model: ${OPENAI_MODEL}
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_KEY}